import Head from 'next/head'
import Link from 'next/link'
import { Bio } from './src/components/Bio'
import Image from 'next/image'
import { Google } from './src/components/Google'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-white'>
      <Head>
        <title>Google (Discounted)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-white">
        {/* <Bio />
        <Link href="/banana">Banana Pic</Link> */}
        <Google name="Sarah"/> 
      </main>
    </div>
  )
}
